//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docnet_final.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuffetTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuffetTicket()
        {
            this.BuffetTicketMenuItems = new HashSet<BuffetTicketMenuItem>();
            this.BuffetTicketTimeSlots = new HashSet<BuffetTicketTimeSlot>();
        }
    
        public int BuffetTicketID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuffetTicketMenuItem> BuffetTicketMenuItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuffetTicketTimeSlot> BuffetTicketTimeSlots { get; set; }
    }
}
