//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docnet_final.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocNetFinalDataBase : DbContext
    {
        public DocNetFinalDataBase()
            : base("name=DocNetFinalDataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuffetTicket> BuffetTickets { get; set; }
        public virtual DbSet<BuffetTicketMenuItem> BuffetTicketMenuItems { get; set; }
        public virtual DbSet<BuffetTicketTimeSlot> BuffetTicketTimeSlots { get; set; }
        public virtual DbSet<CategoryFood> CategoryFoods { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<ServingTable> ServingTables { get; set; }
    }
}
