//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace docnet_final.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServingTable
    {
        public int ServingTableID { get; set; }
        public string ServingTableCode { get; set; }
        public int Capacity { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
